### ISSUE TITLE
Unable to find container when used in Swarm stack

### ISSUE THREAD

**Issue by blackfeather9** [rcdailey/nextcloud-cronjob#14]
The nextcloud-cronjob container is working great for my docker-compose setup with the following configuration:
```
  nextcloud-cron:
    image: rcdailey/nextcloud-cronjob
    container_name: nextcloud-cron
    restart: unless-stopped
    network_mode: none
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CRONSCRIPTS}:/cron-scripts:ro
    environment:
      - NEXTCLOUD_CONTAINER_NAME=nextcloud-app
    depends_on:
      - nextcloud-app
```
I am now migrating to a swarm service, but it doesn't appear I can use this same cron solution. My understanding is that the swarm naming scheme, due to replicas and unique service names, is not compatible. Example:

As single docker-compose file:
```
user@docker:$ docker ps --format '{{.Names}},{{.ID}}'
nextcloud-app,84195755d4f2
nextcloud-db,9f027708cd03
nextcloud-redis,7c491729a707

```
Converted to swarm stack named "nextcloud":
```
user@docker:$ docker ps --format '{{.Names}},{{.ID}}'
nextcloud_nextcloud-app.1.na20bhtl91z98j8lr5hjjgq69,a61e78034e9d
nextcloud_nextcloud-db.1.tuysjjdnuzetk84y4jmcejeco,86fa6784f9e7
nextcloud_nextcloud-redis.1.yn4h476s5jgp2asjqmb8ezhrp,f12b9876b2c3
```
Is it possible to get the swarm container names and use them with your cron container? I think your container is the best cron solution for nextcloud. Using official `nextcloud:22-apache` base image.

**Comment by blackfeather9** [comment]
Thank you for updating the script. I pulled the new image but it still doesn't find the nextcloud app container in swarm, reporting
```
Container Name: nextcloud_app
ERROR: Unable to find the Nextcloud container
```
Here is an example:
```
user@docker:$ docker node ps
ID             NAME                   IMAGE                               NODE       DESIRED STATE   CURRENT STATE           ERROR                       PORTS
anqjcgj5ttbr   nextcloud_app.1        nextcloud:22-apache                 docker00   Running         Running 1 second ago                                
stmdex4ylnou   nextcloud_cron.1       rcdailey/nextcloud-cronjob:latest   docker00   Ready           Ready 2 seconds ago                                 
ivx8pxed9mug    \_ nextcloud_cron.1   rcdailey/nextcloud-cronjob:latest   docker00   Shutdown        Failed 2 seconds ago    "task: non-zero exit (1)"   
nba79awtovml   nextcloud_db.1         mariadb:10                          docker00   Running         Running 3 seconds ago                               
bzld6fgbgtab   nextcloud_redis.1      redis:6                             docker00   Running         Running 2 seconds ago                             
```
Then running the first part of the find command:
```
user@docker:$ docker ps --format '{{.Names}},{{.ID}}'
nextcloud_app.1.anqjcgj5ttbrhoa06xab0vvnt,a9a806fa7934
nextcloud_redis.1.bzld6fgbgtab8xsr2z0vzfaxx,0ba52ef820ad
nextcloud_db.1.nba79awtovmlglb5ejlq3ilk8,a33d3e10dd46
```
Exporting the `containerName` variable, then I run your full docker ps find (lines 13-15) in the host shell, saved to find_container.sh, it finds the correct container.
```
user@docker:$ export containerName=nextcloud_app
user@docker:$ bash find_container.sh 
a9a806fa7934
```
Whereas running your whole script on the host doesn't find anything at all, unless I do this: 
```
user@docker:$ export NEXTCLOUD_PROJECT_NAME=nextcloud
user@docker:$ export containerName=nextcloud_app
user@docker:$ bash find_container_full.sh
a9a806fa7934
0ba52ef820ad
a33d3e10dd46
```
But because there are three possible options, it fails.

**Comment by rcdailey** [comment]
What is the file structure of the project? Can you share the main structure of the services from the YAML? I honestly do not use Docker Swarm, nor have I ever, so I need to understand a little more about how you got the names you are showing me.

**Comment by blackfeather9** [comment]
The project uses docker-compose.yml updated to work in swarm mode. To deploy, I run a simple script that exports all the variables in the compose file, such as `${NCVOL01}` then executes it with `docker stack deploy -c /config/nextcloud/swarm/docker-compose.yml nextcloud` -- where the last word, nextcloud, defines the `nextcloud_` stack name that shows up in `docker node ps`

Here is a gist of full sanitized `docker-compose.yml` -- I've tried many different names for container/project names: https://gist.github.com/blackfeather9/4b63e1a1f4e7536e55b58312f5a71c2b

**Comment by rcdailey** [comment]
I think I see the problem. I didn't see it before. Your container name in a stack is `nextcloud-app`. and the project name is `nextcloud`. So you should have this in your YAML:

```yml
environment:
  - NEXTCLOUD_CONTAINER_NAME=nextcloud-app
  - NEXTCLOUD_PROJECT_NAME=nextcloud
```

**Comment by blackfeather9** [comment]
> I think I see the problem. I didn't see it before. Your container name in a stack is `nextcloud-app`. and the project name is `nextcloud`. So you should have this in your YAML:
> 
> ```yaml
> environment:
>   - NEXTCLOUD_CONTAINER_NAME=nextcloud-app
>   - NEXTCLOUD_PROJECT_NAME=nextcloud
> ```

Thank you, unfortunately it doesn't work with `nextcloud-app`, `nextcloud_app` , `app` and/or omitting the project name variable entirely.

**Comment by MadsBen** [comment]
@rcdailey The problem is in the find-container.sh script.

ENV:
NEXTCLOUD_CONTAINER_NAME=nextcloud_app
project env. is empty/not used.

The docker ps command:
```
docker ps --format '{{.Names}},{{.ID}}' | \
    egrep "^${containerName}${matchEnd}" | \
    awk '{split($0,a,","); print a[2]}'
```

Looks for a container name like this:
`nextcloud_app,a9a806fa7934`

But the container is actually named
`nextcloud_app.1.anqjcgj5ttbrhoa06xab0vvnt,a9a806fa7934`

@blackfeather9 If you remove the "($matchEnd)" part of the docker ps command, it works on Docker Swarm.
```
docker ps --format '{{.Names}},{{.ID}}' | \
    egrep "^${containerName}" | \
    awk '{split($0,a,","); print a[2]}'
```

My egrep skills are not good enough to make a command where you look for `$(containerName)("wildcard")$(matchEnd)$(containerID)`


Edit: Turns out it wasn't that difficult. You need to add `.*` between `$(containerName)` and `$(matchEnd)`. So the line should be:
```
docker ps --format '{{.Names}},{{.ID}}' | \
    egrep "^${containerName}.*${matchEnd}" | \
    awk '{split($0,a,","); print a[2]}'
```

You can as a work around add it to the container name. My compose file looks like this:
```
version: '3.6'
services:
  cron:
    image: rcdailey/nextcloud-cronjob
    depends_on:
    - app
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /etc/localtime:/etc/localtime:ro
    environment:
      NEXTCLOUD_CONTAINER_NAME: "nextcloud_app.*"
      NEXTCLOUD_EXEC_SHELL: "sh"
```
