### ISSUE TITLE
ERROR: Unable to find the Nextcloud container

### ISSUE THREAD

**Issue by Teenspirit** [rcdailey/nextcloud-cronjob#15]
Hi, 

Sorry to bother with what seems like such an easy fix, but I've tried everything and gone through the other issues. The solutions provided doesn't seem to rectify the problem for me.

I am getting the following error described above in the cronjob logs. 

> Will search for Nexcloud container as a Docker Compose service
> Project: nextcloud, Service: nextcloud
> ERROR: Unable to find the Nextcloud container

Below is my config for Nextcloud in docker-compose.yml file:

```
nextcloud:
  <<: *common-keys-apps
  image: nextcloud:stable
  container_name: nextcloud
  hostname: nextcloud
  #ports:
  #  - 3000:80
  # Persistent volumes with bind mounts to easily move/backup data
  volumes:
    - $DOCKERDIR/appdata/nextcloud/html:/var/www/html
    - $DOCKERDIR/appdata/nextcloud/apps:/var/www/html/custom_apps
    - $DOCKERDIR/appdata/nextcloud/config:/var/www/html/config
    - $DOCKERDIR/appdata/nextcloud/data:/var/www/html/data
  # Environment (internal to the container) variables to simplify setup
  environment:
    # Redis host name (container_name)
    - REDIS_HOST=$NEXTCLOUD_REDIS__HOST
    - NEXTCLOUD_TRUSTED_DOMAIN=files.$DOMAINNAME_CLOUD_SERVER
    - TRUSTED_PROXIES=192.168.90.254/24
  labels:
    - "traefik.enable=true"
    ## HTTP Routers
    - "traefik.http.routers.nextcloud-rtr.entrypoints=https"
    - "traefik.http.routers.nextcloud-rtr.rule=Host(`files.$DOMAINNAME_CLOUD_SERVER`)"
    - "traefik.http.routers.nextcloud-rtr.tls=true"
    - “traefik.http.routers.nextcloud-rtr.middlewares=cloud,cloud-dav”
    ## Middlewares
    - "traefik.http.routers.nextcloud-rtr.middlewares=chain-nextcloud@file"
    ## HTTP Services
    - "traefik.http.routers.nextcloud-rtr.service=nextcloud-svc"
    - "traefik.http.services.nextcloud-svc.loadbalancer.server.port=80"
```

And for cron-job config in the same file:

```
cron:
  # <<: *common-keys-core
  image: rcdailey/nextcloud-cronjob
  restart: always
  network_mode: none
  depends_on:
    - nextcloud
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /etc/localtime:/etc/localtime:ro
  environment:
    - NEXTCLOUD_CONTAINER_NAME=nextcloud
    - NEXTCLOUD_PROJECT_NAME=nextcloud
    - NEXTCLOUD_CRON_MINUTE_INTERVAL=5
    #- DEBUG
```

Thank you for your time.
