### ISSUE TITLE
unable to find the nextcloud container

### ISSUE THREAD

**Issue by Ace0fspadev** [rcdailey/nextcloud-cronjob#8]
Hey, first of all thanks for that container, but i have a problem that i cant figure out.

I have used a compose file, with the right container name and the basedir (project) name, i also tried setting the project name in an .env file, it is always the same.

i hope this is not bcs you use nextcloud:apache image...

I also tried switching from compose file version 3 to 3.7
The Debug env variable doesn't seem to do sth in this case.

here is the part of the compose:

```  
  nextcloud:
    depends_on:
      - mariadb
      - redis
      - watchtower
      - av
    image: nextcloud:19
    container_name: nextcloud
    links:
      - av
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|c$
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/da$
      - "traefik.http.middlewares.nextcloud-https.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud-http.entrypoints=http"
      - "traefik.http.routers.nextcloud-http.rule=Host(`cloud.my.domain`)"
      - "traefik.http.routers.nextcloud-http.middlewares=nextcloud-https@docker"
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.my.domain`)"

      # Set "Strict-Transport-Security" HTTP header for enhanced security
      - "traefik.http.middlewares.sts_headers.headers.stsSeconds=15552000"
      - "traefik.http.middlewares.sts_headers.headers.stsIncludeSubdomains=True"

      # nextcloud enable middlewares 
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-caldav@docker,sts_headers"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=le"
      - "com.centurylinklabs.watchtower.enable=true"

    networks:
      - default
    restart: 'unless-stopped'
    volumes:
      - ./data/volumes/nextcloud/html:/var/www/html

  cron:
    image: rcdailey/nextcloud-cronjob
    restart: unless-stopped
    network_mode: none
    container_name: 'cron'
    depends_on:
      - nextcloud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NEXTCLOUD_CONTAINER_NAME=nextcloud
      - NEXTCLOUD_PROJECT_NAME=traefik



```
