### ISSUE TITLE
Can't find docker container

### ISSUE THREAD

**Issue by xzaz** [rcdailey/nextcloud-cronjob#9]
I am trying to get this running but getting into the error that it can't find the docker container.

`docker ps`
```
cb2c6a9f3af2        nextcloud:latest          "/entrypoint.sh apac…"   8 days ago          Up 8 days           0.0.0.0:8080->80/tcp                             NextCloud
```

`docker ps --format '{{.Names}},{{.ID}}' | egrep "NextCloud," | awk '{split($0,a,","); print a[2]}'`
```
cb2c6a9f3af2
``` 

Result in portainer:
```
Container Name: NextCloud,
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?,
ERROR: Unable to find the Nextcloud container,
``` 

Maybe add debug information on this line when debub is enabled?
https://github.com/rcdailey/nextcloud-cronjob/blob/f2ce54653b6f8092da1e3abfd25179a4c7c68e0b/scripts/find-container.sh#L10

**Comment by rcdailey** [comment]
Please share your `docker-compose.yml`. You are likely not mounting the docker unix socket which is required.

**Comment by xzaz** [comment]
I am not using docker-compose; i'v set up a stand alone instance of NextCloud.

**Comment by rcdailey** [comment]
The point of my request was that I need to see your configuration in order to help you. Please provide a `docker-compose.yml` generated by [docker-autocompose](https://github.com/Red5d/docker-autocompose) and I will take a look and see what the issue is.

**Comment by xzaz** [comment]
```
~/docker-autocompose/docker-autocompose$ sudo python3 autocompose.py                                                                                                                                                                                                                                              NextCloud
version: "3"
services:
  NextCloud:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - AUDIT_CONTROL
      - BLOCK_SUSPEND
      - DAC_READ_SEARCH
      - IPC_LOCK
      - IPC_OWNER
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_ADMIN
      - MAC_OVERRIDE
      - NET_ADMIN
      - NET_BROADCAST
      - SYSLOG
      - SYS_ADMIN
      - SYS_BOOT
      - SYS_MODULE
      - SYS_NICE
      - SYS_PACCT
      - SYS_PTRACE
      - SYS_RAWIO
      - SYS_RESOURCE
      - SYS_TIME
      - SYS_TTY_CONFIG
      - WAKE_ALARM
    command:
      - apache2-foreground
    container_name: NextCloud
    entrypoint:
      - /entrypoint.sh
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - 'PHPIZE_DEPS=autoconf           dpkg-dev                file           g                                                                                                                                                                                                                                             ++              gcc             libc-dev                make            pkg-conf                                                                                                                                                                                                                                             ig
                        re2c'
      - PHP_INI_DIR=/usr/local/etc/php
      - APACHE_CONFDIR=/etc/apache2
      - APACHE_ENVVARS=/etc/apache2/envvars
      - PHP_EXTRA_BUILD_DEPS=apache2-dev
      - 'PHP_EXTRA_CONFIGURE_ARGS=--with-apxs2 --disable-cgi'
      - 'PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE                                                                                                                                                                                                                                              -D_FILE_OFFSET_BITS=64'
      - 'PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOUR                                                                                                                                                                                                                                             CE
        -D_FILE_OFFSET_BITS=64'
      - 'PHP_LDFLAGS=-Wl,-O1 -pie'
      - 'GPG_KEYS=42670A7FE4D0441C8E4632349E4FDC074A4EF02D 5A52880781F755608BF81                                                                                                                                                                                                                                             5FC910DEB46F53EA312'
      - PHP_VERSION=7.4.13
      - PHP_URL=https://www.php.net/distributions/php-7.4.13.tar.xz
      - PHP_ASC_URL=https://www.php.net/distributions/php-7.4.13.tar.xz.asc
      - PHP_SHA256=aead303e3abac23106529560547baebbedba0bb2943b91d5aa08fff1f4168                                                                                                                                                                                                                                             0f4
      - NEXTCLOUD_VERSION=20.0.3
      - REDIS_HOST=xx
      - REDIS_HOST_PORT=32770
      - REDIS_HOST_PASSWORD=xx
    hostname: 8b5414d0e15d
    image: nextcloud:latest
    ipc: private
    logging:
      driver: json-file
      options: {}
    mac_address: 02:42:ac:11:00:04
    networks:
      bridge:
        aliases:
    ports:
      - 8080:80/tcp
    volumes:
      - ad1a705d3027e68e933bec9411865d050f61a987a945e03a9bfe87cf1479ae5e:/var/ww                                                                                                                                                                                                                                             w/html
    working_dir: /var/www/html
networks:
  bridge:
    external: true
```

**Comment by rcdailey** [comment]
You have only provided the configuration for the nextcloud container itself. I need to see the configuration of your `rcdailey/nextcloud-cronjob` container.

**Comment by xzaz** [comment]
``` 
~/docker-autocompose/docker-autocompose$ sudo python3 autocompose.py                                  nextcloud-cronjob
version: "3"
services:
  nextcloud-cronjob:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - AUDIT_CONTROL
      - BLOCK_SUSPEND
      - DAC_READ_SEARCH
      - IPC_LOCK
      - IPC_OWNER
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_ADMIN
      - MAC_OVERRIDE
      - NET_ADMIN
      - NET_BROADCAST
      - SYSLOG
      - SYS_ADMIN
      - SYS_BOOT
      - SYS_MODULE
      - SYS_NICE
      - SYS_PACCT
      - SYS_PTRACE
      - SYS_RAWIO
      - SYS_RESOURCE
      - SYS_TIME
      - SYS_TTY_CONFIG
      - WAKE_ALARM
    container_name: nextcloud-cronjob
    entrypoint:
      - tini
      - --
      - /entrypoint.sh
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - NEXTCLOUD_EXEC_USER=www-data
      - NEXTCLOUD_CRON_MINUTE_INTERVAL=15
      - NEXTCLOUD_EXEC_SHELL=bash
      - NEXTCLOUD_EXEC_SHELL_ARGS=-c
      - NEXTCLOUD_CONTAINER_NAME=NextCloud
      - NEXTCLOUD_PROJECT_NAME=
    hostname: 31db06b3c013
    image: rcdailey/nextcloud-cronjob:latest
    ipc: private
    logging:
      driver: json-file
      options: {}
    mac_address: 02:42:ac:11:00:05
    networks:
      bridge:
        aliases:
    restart: unless-stopped
networks:
  bridge:
    external: true
```

Thanks for helping :)
